[package]
name = "collision"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = { version = "0.4.42", features = ["serde"] }
level = { version = "0.1.0", path = "../level" }
serde = { version = "1.0.228", features = ["derive"] }
